import { useState, type CSSProperties } from 'react';
import type { ProfileAudit } from '../domain/profile';

export function Dashboard({ audit, onRestart }: { audit: ProfileAudit; onRestart: () => void }) {
  const [active, setActive] = useState(0);
  const client = audit.clientViews[active];
  return <section className="report"><header className="report-head"><div><p className="eyebrow">Результат · {audit.platform}</p><h1>Почему клиент может не заказать — и что исправить первым</h1>{audit.analysisMode && <div className={audit.analysisMode === 'ai' ? 'analysis-badge ai' : 'analysis-badge'}><b>{audit.analysisMode === 'ai' ? 'AI-анализ' : 'Базовый анализ'}</b><span>{audit.analysisSummary || 'Локальный отчёт готов.'}</span></div>}</div><button className="secondary" onClick={onRestart}>Новый анализ</button></header>
    <div className="score-grid"><article className="score-card"><div className="ring" style={{ '--value': `${audit.score * 3.6}deg` } as CSSProperties}><strong>{audit.score}</strong><span>/ 100</span></div><div><p className="eyebrow">Общий балл</p><h2>Профиль уже можно усилить</h2><p>Оценка показывает, насколько быстро клиент понимает ценность и чувствует уверенность.</p></div></article><article className="metric"><span>Уровень доверия</span><strong>{audit.trust}%</strong><div className="meter"><i style={{ width: `${audit.trust}%` }} /></div><small>{audit.trustLabel ? `${audit.trustLabel} · ` : ''}Вероятность заказа: <b>{audit.likelihood}</b></small></article><article className="barrier"><span>Главный барьер</span><h3>{audit.barrier.title}</h3><p>{audit.barrier.description}</p></article></div>
    <div className="two-col"><section className="panel"><div className="section-title"><div><p className="eyebrow">Приоритеты</p><h2>На что обратить внимание</h2></div><span className="count">5 пунктов</span></div><ol className="issues">{audit.issues.map((item, i) => <li key={i}><b>{item.title}</b><p>{item.description}</p></li>)}</ol></section><section className="panel teal"><p className="eyebrow">Быстрые улучшения</p><h2>Что можно изменить сегодня</h2><ul className="checklist">{audit.quickWins.map((item) => <li key={item}>✓ <span>{item}</span></li>)}</ul><div className="effect"><small>Максимальный эффект</small><b>{audit.maximumEffect}</b></div></section></div>
    <section className="panel clients"><p className="eyebrow">Как профиль видят разные клиенты</p><h2>Выберите взгляд клиента</h2><div className="tabs" role="tablist">{audit.clientViews.map((view, i) => <button key={view.label} role="tab" aria-selected={active === i} className={active === i ? 'tab active' : 'tab'} onClick={() => setActive(i)}>{view.label}</button>)}</div><div className="client-detail"><div><span>Понравится</span><p>{client.likes}</p></div><div><span>Вызовет сомнение</span><p>{client.doubts}</p></div><div><span>Почему может не написать</span><p>{client.reason}</p></div><div><span>Что исправить</span><p>{client.action}</p></div></div></section>
    {audit.categories?.length ? <section className="panel category-panel"><p className="eyebrow">Карта доверия</p><h2>Категории анализа</h2><div className="category-grid">{audit.categories.map((category) => <article key={category.name}><div><b>{category.name}</b><span className={category.status === 'Хорошо' ? 'good' : category.status === 'Средне' ? 'medium' : 'needs'}>{category.status}</span></div><strong>{category.score}</strong><i><em style={{ width: `${category.score}%` }} /></i><p>{category.explanation}</p><small>{category.recommendation}</small></article>)}</div></section> : null}
    {audit.missingDataWarnings?.length ? <section className="warnings"><b>Что стоит добавить в профиль</b>{audit.missingDataWarnings.map((warning) => <span key={warning}>{warning}</span>)}</section> : null}
    <section className="improvements"><div className="section-title"><div><p className="eyebrow">Готовые улучшения</p><h2>Перепишите профиль спокойнее и конкретнее</h2></div></div><div className="improve-grid"><article><span>Новый заголовок</span><h3>{audit.improvements.headline}</h3></article><article><span>Описание профиля</span><p>{audit.improvements.description}</p></article><article><span>До / после</span><p className="before">До: {audit.improvements.before}</p><p className="after">После: {audit.improvements.after}</p></article><article><span>Следующий шаг</span><p>{audit.improvements.portfolio}</p><p>{audit.improvements.price}</p></article></div></section>
    {audit.competitive ? <section className="panel competitive-panel"><p className="eyebrow">Конкурентный анализ</p><h2>Как выглядеть сильнее на фоне конкурентов</h2><div className="competitive-grid">{audit.competitive.competitors.map((competitor) => <article key={competitor.name}><b>{competitor.name}</b><p><strong>У конкурента:</strong> {competitor.strengths.join(', ') || 'явных преимуществ по сигналам нет'}</p><p><strong>У вас:</strong> {competitor.userAdvantages.join(', ') || 'нет явного преимущества по сигналам'}</p></article>)}</div><ul className="checklist">{audit.competitive.actions.map((action) => <li key={action}>✓ <span>{action}</span></li>)}</ul></section> : null}
  </section>;
}
